---

version: 2.1

jobs:

  build:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2004:202010-01
    environment:
      ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
      PYTHONPATH: /usr/lib/python3/dist-packages

    steps:
      - run: sudo rm -f /etc/apt/sources.list.d/google* /etc/apt/sources.list.d/heroku*
      - run: ls -lh /etc/apt/sources.list.d/
      - run: sudo apt remove --assume-yes --purge apparmor
      - run: sudo apt update
      - run: sudo apt install tree ansible ansible-lint

      - run: ansible --version
      - run: ansible-lint --version

      - checkout

      - run: printf '[defaults]\nroles_path=../' > ansible.cfg
      - run: ansible-lint

      # dependencies
      - run: ansible-galaxy install lifeofguenter.mongodb

      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local

      - run:
          command: sudo journalctl --no-pager --unit=unifi
          when: on_fail
      - run:
          command: sudo cat /var/log/unifi/server.log
          when: on_fail

      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local

      - run: sudo cat /var/log/unifi/server.log
      - run: sudo journalctl --no-pager --unit=unifi
      - run: mongod --version
