---

- name: Reload_systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: Restart_unifi
  ansible.builtin.systemd:
    name: unifi
    state: restarted
    enabled: yes
  become: yes
