---

- name: Reload_systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart_unifi
  ansible.builtin.systemd:
    name: unifi
    state: restarted
    enabled: true
  become: true
